/**
 * v1.2 — Director Route 2.0 plan step.
 *
 * The very first entry in the run log. Captures the model's
 * (or our pre-baked) plan for the loop — "I will search
 * trends, draft a prompt, critique, refine, finalize" — so
 * the Replay UI can show *why* the agent took the actions it
 * did, not just *what* it did.
 *
 * Two exports:
 *   - `buildDirectorPlan(context)` returns the plan text.
 *   - `buildDirectorSystemPrompt(context)` returns the full
 *     system prompt the model sees; it embeds the plan and the
 *     niche/genre/angle orientation. The same context is also
 *     passed to the user prompt (`buildUserPrompt`).
 *
 * The system prompt deliberately calls out the 6-step loop
 * shape (`plan → search → draft → critique → refine →
 * finalize`) so a model that's not familiar with the
 * director pattern still produces a predictable tool-call
 * sequence. The model is free to skip steps (e.g. if the
 * angle is already obvious, it can go straight to
 * `generate_prompt`), but the upper bound is enforced by
 * Vercel AI SDK's `stopWhen: stepCountIs(8)`.
 *
 * The plan is pure (no IO, no time) so the unit test can
 * snapshot the output and catch regressions when the
 * system prompt is edited.
 */
import type { SkillRef } from '@/lib/agent-tools/schemas';
// M1 CANON-WIRING: the Director is the AIart4never Studio Director generating
// on-canon Master4never multiverse art. The canon block (full persona + locked
// look + hard rules + reality hallmarks + persistence mandate) is injected into
// the director system prompt so every drafted prompt stays on-model.
import {
  buildCanonSystemBlock,
  buildCharacterLockBlock,
  type CharacterId,
} from '@/lib/canon';

export interface PlanContext {
  niches: string[];
  genres: string[];
  ideaConcept: string;
  skillContext?: SkillRef[];
  /**
   * M1 CANON-WIRING: the active Master4never canon character whose persona +
   * locked look + hard rules shape the director's drafts. Defaults to 'kael'
   * (the protagonist / narrator) when the caller omits it.
   */
  characterId?: CharacterId;
}

/**
 * The 6-step plan the model is told to follow. Returned as a
 * single string so it can be embedded in the system prompt
 * and also stored as the first step's `reasoning` field.
 */
export function buildDirectorPlan(context: PlanContext): string {
  const nichesLine =
    context.niches.length > 0
      ? `I will search for trends in: ${context.niches.join(', ')}.`
      : 'No niches supplied — I will skip the trending-search step and draft from the angle alone.';

  const skillsLine =
    context.skillContext && context.skillContext.length > 0
      ? `Active skills to fold into the draft: ${context.skillContext.map((s) => s.name).join(', ')}.`
      : 'No skills active — the draft will use the base persona only.';

  return [
    'Director plan (executed in this order, stop early if budget is exhausted):',
    `1. (Optional) trending_search({niches, ideaConcept}) — pull a few trending hits for context.`,
    `2. generate_prompt({niches, genres, angle, skillContext, trendingContext?}) — produce the first draft.`,
    `3. critique_prompt({prompt, requirements}) — score 0..1. If score < 0.7, refine.`,
    `4. (Optional, max 2 refine passes) generate_prompt again with the critique's issues as extra context.`,
    `5. Finalize: output the final prompt as the assistant text (no tool call).`,
    `6. Stop. The route layer captures the result.`,
    '',
    nichesLine,
    skillsLine,
    `Angle (the on-canon Master4never concept to realise): "${context.ideaConcept}".`,
  ].join('\n');
}

/**
 * The full system prompt. Pre-baked (not generated by the
 * model) so the Replay UI can render the same string the
 * model saw, and so the test suite can pin the wording.
 */
export function buildDirectorSystemPrompt(context: PlanContext): string {
  const plan = buildDirectorPlan(context);
  const characterId: CharacterId = context.characterId ?? 'kael';
  // M1 CANON-WIRING: the director now generates on-canon Master4never
  // multiverse art (NOT third-party crossovers). The canon block carries the
  // active character's persona, locked look, hard rules, reality hallmarks,
  // and the persistence/Element mandate so every drafted prompt stays on-model.
  const canonBlock = buildCanonSystemBlock(characterId);
  // M1 CANON-WIRING (#4): the compact identity-lock fragment for the active
  // character — the SAME-man lock + the Higgsfield Element anchor token
  // (`<<<id>>>`). We append it to the IMAGE-PROMPT instructions (rather than
  // threading it through the model-filled generate_prompt tool input, which
  // would be unreliable) so every drafted image prompt carries the Element
  // token + lock verbatim. See the report for the rationale on this path.
  const lockBlock = buildCharacterLockBlock(characterId);

  return [
    'You are the AIart4never Studio Director — the agent that plans and writes on-canon image prompts for the Master4never multiverse. Every prompt you draft realises the operator\'s ORIGINAL fictional universe and its locked recurring characters; never lean on copyrighted franchises, brands, trademarks, or named third-party characters.',
    '',
    canonBlock,
    '',
    'You operate a multi-step tool-use loop. The plan below is the recommended shape — feel free to skip steps when they are not needed, but always end with a final assistant text containing the prompt the user will use.',
    '',
    plan,
    '',
    'Rules:',
    '- Every tool call MUST match the JSON schema declared by the tool (the AI SDK enforces this; the route will surface a 4xx if you slip).',
    '- critique_prompt is the quality gate. If score < 0.7, regenerate the draft at most twice — do not loop forever.',
    '- When the draft renders the active canon character, embed the identity lock below verbatim into the image prompt — keep the SAME man (face + bone structure + features), carry the Anchor element token so the look never drifts:',
    lockBlock,
    '- The final assistant text is what the user sees. It MUST be the prompt draft (40-150 words), not a summary, not JSON, not a markdown fence.',
    '- If a tool returns an error part, you may try once more with adjusted input. If it still fails AND you cannot produce a usable prompt, finalize with exactly "DIRECTOR_FAILED: <one short sentence naming the issue>" — never a free-form apology. (The pipeline detects this sentinel and falls back to the verbatim concept; an undetected explanation would be sent to the image model as the prompt.)',
  ].join('\n');
}

/**
 * The single user-message the loop is started with. Kept
 * short on purpose — the system prompt carries the plan, the
 * user message carries the brief.
 */
export function buildUserPrompt(context: PlanContext): string {
  return [
    `Angle: ${context.ideaConcept}`,
    '',
    `Niches: ${context.niches.join(', ') || '(none)'}`,
    `Genres: ${context.genres.join(', ') || '(none)'}`,
    '',
    'Execute the director plan and return the final prompt as your terminal assistant text.',
  ].join('\n');
}

/**
 * Build the initial `plan` step that goes at idx 0 of the log.
 * The step is *not* generated by the model — it's a pre-baked
 * record so the Replay UI has the plan to render even when the
 * model is mocked.
 */
export function buildInitialPlanStep(
  context: PlanContext,
  opts: { timestamp?: number; clock?: () => number } = {},
): { type: 'plan'; reasoning: string; cost: number; timestamp: number } {
  const clock = opts.clock ?? (() => Date.now());
  return {
    type: 'plan',
    reasoning: buildDirectorPlan(context),
    cost: 0,
    timestamp: opts.timestamp ?? clock(),
  };
}
